baseURL = "https://EOS-Info.github.io/eo-satelites-characteristics/"

languageCode = 'en-us'
title = 'Satellite Characteristics'
theme = 'PaperMod'

[params]
  defaultTheme = "dark"
  homeInfoParams = { Title = "EO Satellite Index"}
  related = false
  paginate = 0

[[menu.main]]
  name = "Satellites"
  url = "/satellite-characteristics/satellites/"
  weight = 1
